/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Resto.Serveur;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.*;
import java.text.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Adrien
 */

public class DialogLogin extends javax.swing.JDialog {

    private boolean MPgood;
    private String nomServeur;
    
    private Properties propLogin;
    private Properties propConfig;
    
   
    /**
     * Creates new form DialogLogin
     */
    public DialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        propLogin = new Properties();
        String outfile = System.getProperty("user.dir") + "\\Login.properties";
        File monFile = new File(outfile);
        try
        {
            propLogin.load (new FileInputStream (monFile));
        }
        catch (FileNotFoundException e) { System.out.println("Fichier de propriétés non trouvé !"); }
        catch (IOException e) { System.out.println("Aie : " + e.getMessage()); }
        
        propConfig = new Properties();
        outfile = System.getProperty("user.dir") + "\\Config.properties";
        monFile = new File(outfile);
        try
        {
            propConfig.load (new FileInputStream (monFile));
        }
        catch (FileNotFoundException e) { System.out.println("Fichier de propriétés non trouvé !"); }
        catch (IOException e) { System.out.println("Aie : " + e.getMessage()); }
        
        setTitle("Restaurant \"" + propConfig.getProperty("nomRestaurant"));
        initComponents();
        setMPgood(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPassword = new javax.swing.JLabel();
        jLabelServer = new javax.swing.JLabel();
        jTextFieldServer = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonConnectAttempt = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JPasswordField();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());

        jLabelPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelPassword.setText("MOT DE PASSE :");

        jLabelServer.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelServer.setText("SERVEUR :");

        jTextFieldServer.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServerActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Annuler");
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonConnectAttempt.setText("Se connecter");
        jButtonConnectAttempt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConnectAttempt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectAttemptActionPerformed(evt);
            }
        });

        jTextFieldPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        dateLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelServer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldServer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldPassword))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButtonConnectAttempt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServer)
                    .addComponent(jTextFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonConnectAttempt))
                .addGap(100, 100, 100))
        );

        Date date = new Date( );

        DateFormat format = DateFormat.getInstance( );

        DateFormat format_fr = DateFormat.getDateInstance(DateFormat.FULL, Locale.FRENCH);

        SimpleDateFormat h = new SimpleDateFormat ("HH:mm");
        Date heure = new Date();

        dateLabel.setText(format_fr.format(date)+", "+ h.format(heure));
        // Appliquer le format à la date
        // Code adding the component to the parent container - not shown here

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonConnectAttemptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectAttemptActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldServer.getText().isEmpty() || jTextFieldPassword.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Veuillez renseigner tous les champs.", "Attention", JOptionPane.INFORMATION_MESSAGE);
        
        else
        {
            if(propLogin.getProperty(jTextFieldServer.getText()) == null ? jTextFieldPassword.getText() != null : !propLogin.getProperty(jTextFieldServer.getText()).equals(jTextFieldPassword.getText()))
            {
                JOptionPane.showMessageDialog(null, "Mot de passe incorrect", "Attention", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldPassword.setText("");
            }
            
            else
            {   
                setMPgood(true);
                setNomServeur(jTextFieldServer.getText());
                dispose();
            }
        }
    }//GEN-LAST:event_jButtonConnectAttemptActionPerformed

    private void jTextFieldServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLogin dialog = new DialogLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConnectAttempt;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelServer;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldServer;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the MPgood
     */
    public boolean isMPgood() {
        return MPgood;
    }

    /**
     * @param MPgood the MPgood to set
     */
    public void setMPgood(boolean MPgood) {
        this.MPgood = MPgood;
    }

    /**
     * @return the nomServeur
     */
    public String getNomServeur() {
        return nomServeur;
    }

    /**
     * @param nomServeur the nomServeur to set
     */
    public void setNomServeur(String nomServeur) {
        this.nomServeur = nomServeur;
    }
}
