/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Resto.Table;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import javax.swing.ButtonGroup;
import legourmetaudacieux.ThreadImprimer;

/**
 *
 * @author Adrien et Jean
 */
public class EncaisserFrame extends javax.swing.JDialog {

    /**
     * @return the Encaisser
     */
    public boolean isEncaisser() {
        return Encaisser;
    }

    /**
     * @param Encaisser the Encaisser to set
     */
    public void setEncaisser(boolean Encaisser) {
        this.Encaisser = Encaisser;
    }

    /**
     * @return the addition
     */
    public float getAddition() {
        return addition;
    }

    /**
     * @param addition the addition to set
     */
    public void setAddition(float addition) {
        this.addition = addition;
    }
    private Properties prop;
    private Table tableEncaisser;
    private boolean Encaisser;
    private float addition;
    /**
     * Creates new form EncaisserFrame
     */
    public EncaisserFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Restaurant \"Le gourmet audacieux\"");
        initComponents();
        
        ButtonGroup group = new ButtonGroup();
        group.add(consulterRadioButton);
        group.add(imprimerRadioButton);
        group.add(encaisserRadioButton);
    }
    
    public EncaisserFrame(java.awt.Frame parent, boolean modal, Table t) {
        super(parent, modal);
        
        prop = new Properties();
        String outfile = System.getProperty("user.dir") + "\\config.properties";
        File monFile = new File(outfile);
        try
        {
            prop.load (new FileInputStream (monFile));
        }
        catch (FileNotFoundException e) { System.out.println("Fichier de propriétés non trouvé !"); }
        catch (IOException e) { System.out.println("Aie : " + e.getMessage()); }
        
        setTitle("Restaurant \"" + prop.getProperty("nomRestaurant"));
        initComponents();
        table.setText(t.getNumTable());
        nbCouvert.setText(String.valueOf(t.getNbCouvertsEnCours()));
        aPayer.setText(String.valueOf(t.getAddition() + t.getPrixBoissons()) + " EUR");
        
        ButtonGroup group = new ButtonGroup();
        group.add(consulterRadioButton);
        group.add(imprimerRadioButton);
        group.add(encaisserRadioButton);
        
        tableEncaisser = t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableLabel = new javax.swing.JLabel();
        nbCouvertsLabel = new javax.swing.JLabel();
        aPayerLabel = new javax.swing.JLabel();
        table = new javax.swing.JLabel();
        nbCouvert = new javax.swing.JLabel();
        aPayer = new javax.swing.JLabel();
        consulterRadioButton = new javax.swing.JRadioButton();
        imprimerRadioButton = new javax.swing.JRadioButton();
        encaisserRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());

        tableLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        tableLabel.setText("Table :");

        nbCouvertsLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        nbCouvertsLabel.setText("Nombre de couverts :");

        aPayerLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        aPayerLabel.setText("A PAYER :");

        table.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        nbCouvert.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        aPayer.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        consulterRadioButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        consulterRadioButton.setSelected(true);
        consulterRadioButton.setText("Consulter");
        consulterRadioButton.setToolTipText("Juste pour voir");
        consulterRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imprimerRadioButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        imprimerRadioButton.setText("Imprimer");
        imprimerRadioButton.setToolTipText("Fabriquer souche");
        imprimerRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        encaisserRadioButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        encaisserRadioButton.setText("Encaisser");
        encaisserRadioButton.setToolTipText("Enregistrer le paiement");
        encaisserRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        okButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        okButton.setText("OK");
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        annulerButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        annulerButton.setText("Annuler");
        annulerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aPayerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aPayer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nbCouvertsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbCouvert))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(table)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(consulterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(imprimerRadioButton)
                .addGap(89, 89, 89)
                .addComponent(encaisserRadioButton)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(annulerButton)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableLabel)
                    .addComponent(table))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbCouvertsLabel)
                    .addComponent(nbCouvert))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aPayerLabel)
                    .addComponent(aPayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulterRadioButton)
                    .addComponent(imprimerRadioButton)
                    .addComponent(encaisserRadioButton))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(annulerButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        String choix = "";
        if(consulterRadioButton.isSelected())
            choix = "Consulter";
        else if(imprimerRadioButton.isSelected())
        {
            choix = "Imprimer";
            ThreadImprimer imp = new ThreadImprimer(prop.getProperty("date.format"));
            imp.start();
        }
        else if(encaisserRadioButton.isSelected())
        {
            choix = "Encaisser";
            setEncaisser(true);
            setAddition(tableEncaisser.getAddition());
            
            tableEncaisser.setNbCouvertsEnCours(0);
            tableEncaisser.setPaye(true);
            tableEncaisser.setPrixBoissons(0);
            tableEncaisser.setAddition(0);
            tableEncaisser.getCommandesPlat().clear();
            tableEncaisser.getPlatServi().clear();
        }
        
        System.out.println("Option choisie: " + choix);
        
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncaisserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncaisserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncaisserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncaisserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EncaisserFrame dialog = new EncaisserFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aPayer;
    private javax.swing.JLabel aPayerLabel;
    private javax.swing.JButton annulerButton;
    private javax.swing.JRadioButton consulterRadioButton;
    private javax.swing.JRadioButton encaisserRadioButton;
    private javax.swing.JRadioButton imprimerRadioButton;
    private javax.swing.JLabel nbCouvert;
    private javax.swing.JLabel nbCouvertsLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel table;
    private javax.swing.JLabel tableLabel;
    // End of variables declaration//GEN-END:variables
}
