/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

/**
 *
 * @author Adrien
 */


public class ServeurEnCours extends javax.swing.JDialog {
    
    private Properties prop;
    private void setProperty()
    {
         prop = new Properties();
        String outfile = System.getProperty("user.dir") + "\\config.properties";
        File monFile = new File(outfile);
        try
        {
            prop.load (new FileInputStream (monFile));
        }
        catch (FileNotFoundException e) { System.out.println("Fichier de propriétés non trouvé !"); }
        catch (IOException e) { System.out.println("Aie : " + e.getMessage()); }
    }
    /**
     * Creates new form ServeurEnCours
     */
    private MainSalle mainwindow;
    
    public ServeurEnCours(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setProperty();
        setTitle("Restaurant \"" + prop.getProperty("nomRestaurant"));
        initComponents();
    }
    
    public ServeurEnCours(java.awt.Frame parent, boolean modal, MainSalle m) {
        super(parent, modal);
        setProperty();
        setTitle("Restaurant \"" + prop.getProperty("nomRestaurant"));
        initComponents();
        mainwindow = m;
        nomServeurLabel.setText(mainwindow.getServeurEnCours());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serveurEnCoursLabel = new javax.swing.JLabel();
        nomServeurLabel = new javax.swing.JLabel();
        ouiButton = new javax.swing.JButton();
        nonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());

        serveurEnCoursLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        serveurEnCoursLabel.setText("Serveur en cours :");

        nomServeurLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        ouiButton.setText("Oui");
        ouiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ouiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiButtonActionPerformed(evt);
            }
        });

        nonButton.setText("Non");
        nonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(ouiButton)
                .addGap(109, 109, 109)
                .addComponent(nonButton)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(serveurEnCoursLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomServeurLabel)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serveurEnCoursLabel)
                    .addComponent(nomServeurLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouiButton)
                    .addComponent(nonButton))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ouiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiButtonActionPerformed
        // TODO add your handling code here:
        mainwindow.setServeurTable();
        dispose();
    }//GEN-LAST:event_ouiButtonActionPerformed

    private void nonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonButtonActionPerformed
        // TODO add your handling code here:
        DialogLogin changelog = new DialogLogin(null, true);
        changelog.setVisible(true);
        
        if(changelog.isMPgood())
        {
            mainwindow.updateServeur(changelog.getNomServeur());
            mainwindow.setServeurTable();
            dispose();
        }
    }//GEN-LAST:event_nonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServeurEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServeurEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServeurEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServeurEnCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServeurEnCours dialog = new ServeurEnCours(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomServeurLabel;
    private javax.swing.JButton nonButton;
    private javax.swing.JButton ouiButton;
    private javax.swing.JLabel serveurEnCoursLabel;
    // End of variables declaration//GEN-END:variables
}
